# Generated by Django 3.1.4 on 2020-12-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.FloatField(default=100, verbose_name='salary'),
            preserve_default=False,
        ),
    ]
