version: "3.8"

services:

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://credcard:credcard@db:5432/credcard_db
      DEBUG: "True"

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=credcard
      - POSTGRES_USER=credcard
      - POSTGRES_DB=credcard_db
    ports:
      - "5432:5432"